#ifndef CONFIG_H
#define CONFIG_H

#define DEBUG Serial
#define PORT_SENSORS Serial2 // [TODO] change to spare serial port
#define PORT_ENABLE 4
// 
#define PROPERTIES_SAVE_INTERVAL 10000

// WEBGUI
#define WEBGUI_AP_TIMEOUT 60000 * 10
#define WEBGUI_PORT 80

// TEMPERATURE MANAGEMENT
#define TEMP_MAX 28.0
#define TEMP_MIN 26.0
#define TEMP_MEASUREMENT_INTERVAL 60000

// WINDOW ACTUATOR DEFAULTS
#define WINDOW_DURATION 40000
#define WINDOW_DURATION_MARGIN 5000
#define WINDOW_UPDATE_INTERVAL 60000

// PINS
#define PIN_SENS_TEMP_HUM_INTERIOR 14
#define PIN_SENS_TEMP_HUM_EXTERIOR 25
#define PIN_ACT_WINDOW_0 33
#define PIN_ACT_WINDOW_1 32
#define PIN_SENS_WINDOW_ENDSTOP 39

#define PIN_SENS_MOISTURE_ADDR_0 23
#define PIN_SENS_MOISTURE_ADDR_1 19
#define PIN_SENS_MOISTURE_ADDR_2 18
#define PIN_SENS_MOISTURE_ADDR_3 5
#define PIN_SENS_MOISTURE_ENABLE 4
#define PIN_SENS_MOISTURE_P0 12
#define PIN_SENS_MOISTURE_P1 13

#define PORT_FEEDER Serial2
#define PIN_FEEDER_TX 17
#define PIN_FEEDER_RX 16
#define PIN_ACT_FEEDER_VALVE 26
#define PIN_ACT_FEEDER_PUMP 27

#define PIN_SENS_WEBGUI_ENABLE 36
#define PIN_ACT_WEBGUI_ACTIVE 2

// FEEDER
#define FEEDER_RANGE 65123

// MOISTURE SENSORS
#define SENSORS_N 12
#define SENSORS_RESPONSE_TIMEOUT 5000
#define SENSORS_MEASUREMENT_DURATION 5000
#define READINGS 10
#define FIXED_RESISTOR 4630
#define ADC_RESOLUTION 12






#endif